"""
SurakshaAI — Dataset Catalog
==============================
Manages the dataset_registry and collection_logs tables.

Key fixes from review:
  - URLs are stored as plain strings, not Markdown
  - register_all_datasets() uses UPSERT (updates metadata on conflict)
  - Notes do not claim specific row counts (populated by validation)
"""

from __future__ import annotations

import hashlib
import logging
from typing import Dict, Optional

import pandas as pd
from sqlalchemy import text

from src.db.connection import db_session

logger = logging.getLogger(__name__)


# ── Dataset metadata ──────────────────────────────────────────────────────────
# URLs are plain strings. Row counts are NOT included here.
# Actual counts are populated by the validation pipeline.
DATASET_METADATA: Dict[str, dict] = {
    "financial_scams": {
        "source":             "mendeley",
        "url":                "https://data.mendeley.com/datasets/znsk27yk3h/1",
        "local_path":         "data/raw/financial_scams/",
        "format":             "csv",
        "reliability_weight": 1.0,
        "channel":            "sms",
        "notes":              "Primary Indian financial scam dataset. Row count populated after validation.",
    },
    "sms_phishing": {
        "source":             "mendeley",
        "url":                "https://data.mendeley.com/datasets/f45bkkt8pr/1",
        "local_path":         "data/raw/sms_phishing/",
        "format":             "csv",
        "reliability_weight": 1.0,
        "channel":            "sms",
        "notes":              "Purpose-built smishing dataset. Row count populated after validation.",
    },
    "sms_spam": {
        "source":             "kaggle",
        "url":                "https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset",
        "local_path":         "data/raw/sms_spam/",
        "format":             "csv",
        "reliability_weight": 0.8,
        "channel":            "sms",
        "notes":              "UCI SMS spam collection. Majority class is ham. Row count populated after validation.",
    },
    "phishing_email": {
        "source":             "kaggle",
        "url":                "https://www.kaggle.com/datasets/naserabdullahalam/phishing-email-dataset",
        "local_path":         "data/raw/phishing_email/",
        "format":             "csv",
        "reliability_weight": 0.7,
        "channel":            "email",
        "notes":              "Large phishing email dataset. Requires stratified downsampling in Module 2.",
    },
    "indian_banking_sms": {
        "source":             "kaggle",
        "url":                "https://www.kaggle.com/datasets/dshah1612/sms-data",
        "local_path":         "data/raw/indian_banking_sms/",
        "format":             "csv",
        "reliability_weight": 0.9,
        "channel":            "sms",
        "notes":              "Real Indian SMS data. May lack labels — financial keyword filter required in Module 2.",
    },
    "manual_banking": {
        "source":             "manual",
        "url":                None,
        "local_path":         "data/raw/manual_banking/",
        "format":             "csv",
        "reliability_weight": 0.9,
        "channel":            "banking_notification",
        "notes":              "Manually curated banking notifications. Generated by manual_templates.py.",
    },
    "manual_loan": {
        "source":             "manual",
        "url":                None,
        "local_path":         "data/raw/manual_loan/",
        "format":             "csv",
        "reliability_weight": 0.9,
        "channel":            "loan_ad",
        "notes":              "Manually curated loan advertisements. Generated by manual_templates.py.",
    },
    "manual_whatsapp": {
        "source":             "manual",
        "url":                None,
        "local_path":         "data/raw/manual_whatsapp/",
        "format":             "csv",
        "reliability_weight": 0.9,
        "channel":            "whatsapp",
        "notes":              "Manually curated WhatsApp financial chats. Generated by manual_templates.py.",
    },
    "urls": {
        "source":             "kaggle",
        "url":                "https://www.kaggle.com/datasets/sid321axn/malicious-urls-dataset",
        "local_path":         "data/raw/urls/",
        "format":             "csv",
        "reliability_weight": 1.0,
        "channel":            "url",
        "notes":              "Malicious URL dataset. Requires downsampling in Module 2. URL XGBoost model only.",
    },
    "upi": {
        "source":             "synthetic",
        "url":                None,
        "local_path":         "data/raw/upi/",
        "format":             "csv",
        "reliability_weight": 0.9,
        "channel":            "upi",
        "notes":              "Synthetically generated UPI payment strings. UPI XGBoost model only.",
    },
}


class DatasetCatalog:
    """
    Manages dataset_registry and collection_logs.
    Uses UPSERT so metadata updates are reflected on re-registration.
    """

    def register_all_datasets(self) -> None:
        """
        Register all known datasets using UPSERT.
        Metadata is updated on conflict — not silently ignored.
        """
        with db_session() as db:
            for name, meta in DATASET_METADATA.items():
                db.execute(
                    text("""
                        INSERT INTO dataset_registry
                            (dataset_name, source, url, local_path, format,
                             reliability_weight, channel, status, notes)
                        VALUES
                            (:name, :source, :url, :local_path, :format,
                             :weight, :channel, 'pending', :notes)
                        ON CONFLICT (dataset_name)
                        DO UPDATE SET
                            source             = EXCLUDED.source,
                            url                = EXCLUDED.url,
                            local_path         = EXCLUDED.local_path,
                            format             = EXCLUDED.format,
                            reliability_weight = EXCLUDED.reliability_weight,
                            channel            = EXCLUDED.channel,
                            notes              = EXCLUDED.notes,
                            updated_at         = NOW()
                    """),
                    {
                        "name":       name,
                        "source":     meta["source"],
                        "url":        meta.get("url"),
                        "local_path": meta["local_path"],
                        "format":     meta["format"],
                        "weight":     meta["reliability_weight"],
                        "channel":    meta["channel"],
                        "notes":      meta["notes"],
                    },
                )
        logger.info("Registered/updated %d datasets.", len(DATASET_METADATA))

    def update_status(
        self,
        dataset_name: str,
        status: str,
        raw_row_count:   Optional[int] = None,
        valid_row_count: Optional[int] = None,
        fraud_count:     Optional[int] = None,
        safe_count:      Optional[int] = None,
        unknown_count:   Optional[int] = None,
        checksum:        Optional[str] = None,
    ) -> None:
        """Update dataset status and statistics after a pipeline stage."""
        with db_session() as db:
            db.execute(
                text("""
                    UPDATE dataset_registry
                    SET
                        status          = :status,
                        raw_row_count   = COALESCE(:raw_rows,   raw_row_count),
                        valid_row_count = COALESCE(:valid_rows, valid_row_count),
                        fraud_count     = COALESCE(:fraud,      fraud_count),
                        safe_count      = COALESCE(:safe,       safe_count),
                        unknown_count   = COALESCE(:unknown,    unknown_count),
                        checksum_sha256 = COALESCE(:checksum,   checksum_sha256),
                        updated_at      = NOW()
                    WHERE dataset_name = :name
                """),
                {
                    "status":     status,
                    "raw_rows":   raw_row_count,
                    "valid_rows": valid_row_count,
                    "fraud":      fraud_count,
                    "safe":       safe_count,
                    "unknown":    unknown_count,
                    "checksum":   checksum,
                    "name":       dataset_name,
                },
            )
        logger.info("Updated %s → %s", dataset_name, status)

    def log_operation(
        self,
        dataset_name:  str,
        operation:     str,
        status:        str,
        rows_before:   Optional[int] = None,
        rows_after:    Optional[int] = None,
        details:       Optional[str] = None,
        error_message: Optional[str] = None,
    ) -> None:
        """Append a row to collection_logs."""
        with db_session() as db:
            db.execute(
                text("""
                    INSERT INTO collection_logs
                        (dataset_name, operation, status,
                         rows_before, rows_after, details, error_message)
                    VALUES
                        (:name, :op, :status,
                         :before, :after, :details, :error)
                """),
                {
                    "name":    dataset_name,
                    "op":      operation,
                    "status":  status,
                    "before":  rows_before,
                    "after":   rows_after,
                    "details": details,
                    "error":   error_message,
                },
            )

    def get_all_datasets(self) -> pd.DataFrame:
        with db_session() as db:
            result = db.execute(text("SELECT * FROM dataset_registry ORDER BY id"))
            rows   = result.fetchall()
            cols   = list(result.keys())
        return pd.DataFrame(rows, columns=cols)

    def get_dataset(self, dataset_name: str) -> Optional[dict]:
        with db_session() as db:
            result = db.execute(
                text("SELECT * FROM dataset_registry WHERE dataset_name = :name"),
                {"name": dataset_name},
            )
            row = result.fetchone()
            if row is None:
                return None
            return dict(zip(result.keys(), row))

    def get_collection_logs(
        self,
        dataset_name: Optional[str] = None,
    ) -> pd.DataFrame:
        with db_session() as db:
            if dataset_name:
                result = db.execute(
                    text("""
                        SELECT * FROM collection_logs
                        WHERE dataset_name = :name
                        ORDER BY executed_at DESC
                    """),
                    {"name": dataset_name},
                )
            else:
                result = db.execute(
                    text("SELECT * FROM collection_logs ORDER BY executed_at DESC")
                )
            rows = result.fetchall()
            cols = list(result.keys())
        return pd.DataFrame(rows, columns=cols)

    def export_registry_report(self, output_path: str) -> None:
        """Export the dataset registry to CSV for Module 1 report."""
        df = self.get_all_datasets()
        df.to_csv(output_path, index=False)
        logger.info("Registry exported to %s", output_path)

    @staticmethod
    def compute_file_checksum(file_path: str) -> str:
        sha256 = hashlib.sha256()
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                sha256.update(chunk)
        return sha256.hexdigest()

    @staticmethod
    def compute_text_checksum(text_value: str) -> str:
        return hashlib.sha256(text_value.encode("utf-8")).hexdigest()

    def print_summary(self) -> None:
        df = self.get_all_datasets()
        if df.empty:
            print("No datasets registered yet.")
            return
        print("\n" + "=" * 65)
        print(f"{'SurakshaAI — Dataset Registry':^65}")
        print("=" * 65)
        for _, row in df.iterrows():
            print(f"\n  {row['dataset_name']}")
            print(f"    Source  : {row['source']}")
            print(f"    Status  : {row['status']}")
            print(f"    Rows    : raw={row['raw_row_count']}  "
                  f"valid={row['valid_row_count']}  "
                  f"fraud={row['fraud_count']}  "
                  f"safe={row['safe_count']}")
            print(f"    Weight  : {row['reliability_weight']}")
        print("\n" + "=" * 65 + "\n")